### ISSUE TITLE
Include PR and issue templates?

### ISSUE THREAD

**Issue by jsignell** [dask/.github#1]
I noticed recently that distributed doesn't have PR templates. Should the ones from dask be elevated to this repo?

**Comment by jrbourbeau** [comment]
No strong feelings one way or the other from me. Looking at the issue template in the dask repo, it seems copying the template with the "Question about a sub-project" section removed here would be general enough to apply to all repos in the org. It's less clear about the PR template. For example, not all projects may use `black` for formatting, etc.

**Comment by jacobtomlinson** [comment]
This has come up again in dask/community#50 as a way to ensure new issues have at least a `needs-triage` label.

**Comment by jsignell** [comment]
This is doneI imagine thanks to @jacobtomlinson :)
